version: "3.8"

services:
  app:
    build: .
    container_name: fastapi-nginx-app
    restart: always
    ports:
      - "80:80"
    environment:
      - PORT=80
    command: ["/bin/bash", "-c", "./setup_nginx.sh && uvicorn main:app --host 0.0.0.0 --port 8000"]
