# Use the official Nginx image
FROM nginx:latest

# Copy the Nginx config file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80 for external traffic
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
