name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Oracle VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Add known hosts
        run: ssh-keyscan -H 84.8.132.120 >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: |
          ssh -i private_key.pem ubuntu@84.8.132.120 << 'EOF'
          set -e

          echo "🚀 Pulling latest code..."
          cd /home/ubuntu/fastapi-book-project || exit 1
          git pull origin main

          echo "📦 Activating virtual environment and installing dependencies..."
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt

          echo "🔄 Restarting FastAPI service..."
          sudo systemctl restart fastapi

          echo "✅ Deployment successful!"
          EOF  

      - name: Cleanup
        run: rm private_key.pem
