name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Notify Render to Redeploy
        run: |
          echo "Triggering redeployment..."
          curl -X POST -d "" ${{ secrets.RENDER_DEPLOY_HOOK }}
          echo "Deployment request sent to Render."
